name: ci

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: usdotfhwastoldev/carma-base:develop
      env:
        INIT_ENV: "/home/carma/.base-image/init-env.sh"
        TERM: xterm # use xterm to get full display output from build
      options: --user root
    steps:
      - name: Symlink bash to sh
        run: |
          ln -sf /bin/bash /bin/sh # otherwise source command does not work in scripts

      - name: Create src dir
        run: mkdir -p /opt/carma/src

      - name: Checkout
        run: git clone --depth 1 $GITHUB_SERVER_URL/$GITHUB_REPOSITORY -b $GITHUB_REF_NAME /opt/carma/src/CARMANovatelGpsDriver

      - name: Pull deps
        run: |
          source /home/carma/.base-image/init-env.sh
          git clone https://github.com/usdot-fhwa-stol/carma-msgs.git /opt/carma/src/CARMAMsgs --branch develop
          git clone https://github.com/usdot-fhwa-stol/carma-utils.git /opt/carma/src/CARMAUtils --branch develop

      - name: Build Driver
        run: |
          source /home/carma/.base-image/init-env.sh
          export ROS_PARALLEL_JOBS='-j3 -l3' # Try to reduce memory consumption on build
          build-wrapper-linux-x86-64 --out-dir /opt/carma/bw-output bash make_with_coverage.bash -m -e /opt/carma/ -o /opt/carma/coverage_reports/gcov

      - name: Run C++ Tests
        run: |
          source "$INIT_ENV"
          export ROS_PARALLEL_JOBS='-j3 -l3' # Try to reduce memory consumption on build
          bash /opt/carma/make_with_coverage.bash -t -e /opt/carma/ -o /opt/carma/coverage_reports/gcov
